/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Zh-lx Home",
  "description": "Zh-lx 学习知识总结",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "docker-compose",
      "frontmatter": {},
      "regularPath": "/study/docker/docker-compose/docker-compose.html",
      "relativePath": "study/docker/docker-compose/docker-compose.md",
      "key": "v-af66a064",
      "path": "/study/docker/docker-compose/docker-compose.html",
      "headers": [
        {
          "level": 2,
          "title": "docker-compose 是什么",
          "slug": "docker-compose-是什么"
        },
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "Dockerfile",
      "frontmatter": {},
      "regularPath": "/study/docker/Dockerfile/Dockerfile.html",
      "relativePath": "study/docker/Dockerfile/Dockerfile.md",
      "key": "v-323de50e",
      "path": "/study/docker/Dockerfile/Dockerfile.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是 Dockerfile",
          "slug": "什么是-dockerfile"
        },
        {
          "level": 2,
          "title": "基础示例",
          "slug": "基础示例"
        },
        {
          "level": 3,
          "title": "1. 使用 Dockerfile 定制镜像",
          "slug": "_1-使用-dockerfile-定制镜像"
        },
        {
          "level": 3,
          "title": "2. 开始构建镜像",
          "slug": "_2-开始构建镜像"
        },
        {
          "level": 2,
          "title": "指令详解",
          "slug": "指令详解"
        },
        {
          "level": 3,
          "title": "FROM",
          "slug": "from"
        },
        {
          "level": 3,
          "title": "RUN",
          "slug": "run"
        },
        {
          "level": 3,
          "title": "COPY",
          "slug": "copy"
        },
        {
          "level": 3,
          "title": "ADD",
          "slug": "add"
        },
        {
          "level": 3,
          "title": "CMD",
          "slug": "cmd"
        },
        {
          "level": 3,
          "title": "ENTRYPOINT",
          "slug": "entrypoint"
        },
        {
          "level": 3,
          "title": "ENV",
          "slug": "env"
        },
        {
          "level": 3,
          "title": "ARG",
          "slug": "arg"
        },
        {
          "level": 3,
          "title": "VOLUME",
          "slug": "volume"
        },
        {
          "level": 3,
          "title": "EXPOSE",
          "slug": "expose"
        },
        {
          "level": 3,
          "title": "WORKDIR",
          "slug": "workdir"
        },
        {
          "level": 3,
          "title": "USER",
          "slug": "user"
        },
        {
          "level": 3,
          "title": "HEALTHCHECK",
          "slug": "healthcheck"
        },
        {
          "level": 3,
          "title": "ONBUILD",
          "slug": "onbuild"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker exec",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/exec.html",
      "relativePath": "study/docker/docker命令/exec.md",
      "key": "v-6fc9493b",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/exec.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "OPTIONS 配置",
          "slug": "options-配置"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker build",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/build.html",
      "relativePath": "study/docker/docker命令/build.md",
      "key": "v-15b1596d",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/build.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "OPTIONS 配置",
          "slug": "options-配置"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "mya",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-29565000",
      "path": "/"
    },
    {
      "title": "docker create",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/create.html",
      "relativePath": "study/docker/docker命令/create.md",
      "key": "v-00fc6c65",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/create.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "OPTIONS 配置",
          "slug": "options-配置"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker pause",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/pause.html",
      "relativePath": "study/docker/docker命令/pause.md",
      "key": "v-58b49a6d",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/pause.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker kill",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/kill.html",
      "relativePath": "study/docker/docker命令/kill.md",
      "key": "v-3e6f5aa1",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/kill.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "OPTIONS 配置",
          "slug": "options-配置"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker pull",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/pull.html",
      "relativePath": "study/docker/docker命令/pull.md",
      "key": "v-0a4339d3",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/pull.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "OPTIONS 配置",
          "slug": "options-配置"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker ps",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/ps.html",
      "relativePath": "study/docker/docker命令/ps.md",
      "key": "v-3e4478d2",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/ps.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "OPTIONS 配置",
          "slug": "options-配置"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "参数说明",
          "slug": "参数说明"
        }
      ]
    },
    {
      "title": "docker run",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/run.html",
      "relativePath": "study/docker/docker命令/run.md",
      "key": "v-fd4fb466",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/run.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "OPTIONS 配置",
          "slug": "options-配置"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker rm",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/rm.html",
      "relativePath": "study/docker/docker命令/rm.md",
      "key": "v-1d897d27",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/rm.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "OPTIONS 配置",
          "slug": "options-配置"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker restart",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/restart.html",
      "relativePath": "study/docker/docker命令/restart.md",
      "key": "v-278a4fcd",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/restart.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker stop",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/stop.html",
      "relativePath": "study/docker/docker命令/stop.md",
      "key": "v-74ad254e",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/stop.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker start",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/start.html",
      "relativePath": "study/docker/docker命令/start.md",
      "key": "v-77429fed",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/start.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    },
    {
      "title": "docker unpause",
      "frontmatter": {},
      "regularPath": "/study/docker/docker%E5%91%BD%E4%BB%A4/unpause.html",
      "relativePath": "study/docker/docker命令/unpause.md",
      "key": "v-183cf60d",
      "path": "/study/docker/docker%E5%91%BD%E4%BB%A4/unpause.html",
      "headers": [
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": {
      "/study/docker": [
        {
          "title": "docker命令",
          "children": [
            "/study/docker/docker命令/build.md",
            "/study/docker/docker命令/create.md",
            "/study/docker/docker命令/exec.md",
            "/study/docker/docker命令/kill.md",
            "/study/docker/docker命令/pause.md",
            "/study/docker/docker命令/ps.md",
            "/study/docker/docker命令/pull.md",
            "/study/docker/docker命令/restart.md",
            "/study/docker/docker命令/rm.md",
            "/study/docker/docker命令/run.md",
            "/study/docker/docker命令/start.md",
            "/study/docker/docker命令/stop.md",
            "/study/docker/docker命令/unpause.md"
          ]
        },
        {
          "title": "Dockerfile",
          "children": [
            "/study/docker/Dockerfile/Dockerfile.md"
          ]
        },
        {
          "title": "docker-compose",
          "children": [
            "/study/docker/docker-compose/docker-compose.md"
          ]
        }
      ]
    }
  }
}